### ISSUE TITLE
How to set margin between the item in DynamicConstraintLayoutActivity

### ISSUE THREAD

**Issue by HuuNguyen312** [queencodemonkey/presentation-cool-constraintlayout#1]
Hi @queencodemonkey 

How to set margin between the item in DynamicConstraintLayoutActivity ?
Thanks

**Comment by queencodemonkey** [comment]
It's the documentation for `ConstraintSet`: https://developer.android.com/reference/android/support/constraint/ConstraintSet.html#setMargin(int, int, int)

In the future please don't open issues just to ask questions.
